name: Expo Dependencies

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Are we upgrading to `expo@latest`, or just fixing dependencies?
        required: true
        default: fix-dependencies
        options:
          - upgrade-expo
          - fix-dependencies

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: ğŸ—ï¸ Setup repo
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: ğŸ“¦ Upgrade Expo SDK
        if: ${{ inputs.mode == 'upgrade-expo' }}
        run: bash ./upgrade-dependencies.sh --upgrade-expo

      - name: ğŸ’¬ Create new upgrade PR
        if: ${{ inputs.mode == 'upgrade-expo' }}
        uses: peter-evans/create-pull-request@v5
        with:
          branch: automated-upgrade
          reviewers: |
            byCedric
            keith-kurak
          commit-message: 'chore: upgrade expo to `latest`'
          title: Upgraded Expo SDK to `expo@latest`
          body: |
            This PR was automatically created by the [upgrade workflow](./.github/workflows/upgrade.yml).
            Please review the changes and merge it when you're ready.

      - name: ğŸ‘· Fix Expo dependencies
        if: ${{ inputs.mode == 'fix-dependencies' }}
        run: bash ./upgrade-dependencies.sh --fix-dependencies

      - name: ğŸ’¬ Create new fix PR
        if: ${{ inputs.mode == 'fix-dependencies' }}
        uses: peter-evans/create-pull-request@v5
        with:
          branch: automated-fix
          reviewers: |
            byCedric
            keith-kurak
          commit-message: 'chore: fix expo dependencies'
          title: Fixed all Expo SDK dependencies
          body: |
            This PR was automatically created by the [upgrade workflow](./.github/workflows/upgrade.yml).
            Please review the changes and merge it when you're ready.

      - name: ğŸ“‹ Uploading logs
        uses: actions/upload-artifact@v4
        with:
          path: |
            .sdk-upgrade-logs
            .sdk-fix-logs
